source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'

gem 'builder'
gem 'nokogiri'
gem 'redcarpet'
gem 'rouge'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'slim'
